### PR TITLE
Svg style documentation

### PR DESCRIPTION
**Pull request by Saegrov**

### CODE REVIEW

**Comment by eirikbacker** [comment]
Any updates on this one @Saegrov? :)

**Comment by Saegrov** [comment]
Added an initial draft. @eirikbacker Care to take a design look? I'll update the content.

**Comment by eirikbacker** [comment]
Closes #23. @Saegrov I updated the formatting a bit, please check if it is a-okay, and I'll merge 👍

**Comment by Saegrov** [comment]
@eirikbacker LGTM

**Pull request merged**
